### ISSUE TITLE
visual feature abour charades i3d 

### ISSUE THREAD

**Issue by onlyonewater** [Xun-Yang/Causal_Video_Moment_Retrieval#1]
hi, the link about `charades i3d features` is expired, can you repair it?? thanks!!!

**Comment by Xun-Yang** [comment]
yes, I will re-upload the feature and let you know once it is done.

**Comment by Xun-Yang** [comment]
> hi, the link about `charades i3d features` is expired, can you repair it?? thanks!!!

Fixed.

**Comment by onlyonewater** [comment]
ok, thanks!!!
